version: "3.7"

services:

  movie-service:
    build: 
      context: ./
      dockerfile: ./movieService/Dockerfile
    container_name: movie-service
    restart: unless-stopped

  
  page-gen:
    build: 
      context: ./
      dockerfile: ./pageGen/Dockerfile
    container_name: page-gen
    restart: unless-stopped
    depends_on: 
      - movie-service

  nginx:
    build: ./nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - page-gen
